#!/usr/bin/env python3
"""Generate the bundled provider-mark table from a pinned Simple Icons package.

Simple Icons supplies normalized 24x24 vector paths. We only include entries whose metadata
points back to a provider-owned product, brand page, press kit, or source repository. Providers
without such an asset stay out of this table and deliberately render as coloured lettermarks.

Usage:
  python3 scripts/generate-provider-marks.py \
    --simple-icons-dir /path/to/simple-icons/package
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


PROVIDERS = [
    ("anthropic", "anthropic"),
    ("gemini", "googlegemini"),
    ("supabase", "supabase"),
    ("vercel", "vercel"),
    ("github", "github"),
    ("cloudflare", "cloudflare"),
    ("stripe", "stripe"),
    ("resend", "resend"),
    ("app-store-connect", "appstore"),
    ("apple-notary", "apple"),
    ("apns", "apple"),
    ("developer-id", "apple"),
    ("google-cloud", "googlecloud"),
    ("ga4", "googleanalytics"),
    ("firebase-admin", "firebase"),
    ("search-console", "googlesearchconsole"),
    ("openrouter", "openrouter"),
    ("deepseek", "deepseek"),
    ("kimi", "kimi"),
    ("minimax", "minimax"),
    ("alibaba-bailian", "alibabacloud"),
    ("neon", "neon"),
    ("railway", "railway"),
    ("render", "render"),
    ("netlify", "netlify"),
    ("flyio", "flydotio"),
    ("sentry", "sentry"),
    ("posthog", "posthog"),
    ("npm", "npm"),
    ("pypi", "pypi"),
    ("dockerhub", "docker"),
    ("gitlab", "gitlab"),
    ("mailgun", "mailgun"),
    ("telegram", "telegram"),
]


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--simple-icons-dir", required=True, type=Path)
    args = parser.parse_args()

    package = args.simple_icons_dir.resolve()
    metadata = json.loads((package / "data/simple-icons.json").read_text())
    by_slug = {entry["slug"]: entry for entry in metadata}
    version = json.loads((package / "package.json").read_text())["version"]

    rows = []
    for provider_id, slug in PROVIDERS:
        entry = by_slug[slug]
        source = entry["source"]
        if not source.startswith("https://"):
            raise ValueError(f"{slug}: source is not HTTPS: {source}")
        svg = (package / f"icons/{slug}.svg").read_text()
        match = re.fullmatch(
            r'<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>.*?</title><path d="([^"]+)"/></svg>\n?',
            svg,
        )
        if not match:
            raise ValueError(f"{slug}: unexpected SVG shape")
        rows.append((provider_id, match.group(1), entry["hex"], source))

    output = [
        "// Generated by scripts/generate-provider-marks.py; do not edit by hand.",
        f"// Vector paths: Simple Icons {version}; each source URL points to the provider-owned origin.",
        "",
        "extension ProviderMarks {",
        "    static let bundledOfficialMarks: [String: Mark] = [",
    ]
    for provider_id, path, color, source in rows:
        output.append(
            f'        "{provider_id}": Mark(path: "{swift_string(path)}", '
            f'brandHex: "{color}", source: "{swift_string(source)}"),'
        )
    output.extend(["    ]", "}", ""])

    destination = Path(__file__).resolve().parents[1] / "Sources/KeyKeeperApp/ProviderMarks.generated.swift"
    destination.write_text("\n".join(output))


if __name__ == "__main__":
    main()
