#!/usr/bin/env python3
"""Pin provider-owned artwork once, then sync the App and landing logo wall.

Usage:
  python3 scripts/sync-provider-artwork.py \
    --assets-dir /tmp/provider-logo-downloads \
    --website-wall /absolute/path/to/keykeeper-landing/app/providerWall.json

Download the URLs in Assets/ProviderLogos/sources.json into --assets-dir first.
The pinned SHA-256 prevents a changed favicon (or an HTML error page) from silently
becoming a KeyKeeper mark. `sips` is macOS-owned and produces a small PNG from PNG,
ICO, or SVG without changing the source's aspect ratio.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import json
import re
import subprocess
import tempfile
from pathlib import Path


PROJECT = Path(__file__).resolve().parents[1]
MANIFEST = PROJECT / "Assets/ProviderLogos/sources.json"
SWIFT = PROJECT / "Sources/KeyKeeperApp/ProviderMarks.sourced.generated.swift"


def swift_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def build(assets_dir: Path, website_wall: Path) -> tuple[str, str]:
    entries = json.loads(MANIFEST.read_text())
    wall = json.loads(website_wall.read_text())
    by_id = {entry["id"]: entry for entry in wall}
    if len(by_id) != len(wall):
        raise ValueError("website wall has duplicate brand IDs")

    lines = [
        "// Generated by scripts/sync-provider-artwork.py; do not edit by hand.",
        "// Artwork is pinned by Assets/ProviderLogos/sources.json and bundled offline.",
        "",
        "extension ProviderMarks {",
        "    static let sourcedProviderMarks: [String: Mark] = [",
    ]
    seen_ids: set[str] = set()
    seen_wall_ids: set[str] = set()
    for entry in entries:
        provider_id = entry["id"]
        wall_id = entry["wallId"]
        source = entry["source"]
        brand = entry["brandHex"]
        if provider_id in seen_ids or wall_id in seen_wall_ids:
            raise ValueError(f"duplicate artwork mapping: {provider_id} / {wall_id}")
        seen_ids.add(provider_id)
        seen_wall_ids.add(wall_id)
        if not source.startswith("https://") or not re.fullmatch(r"[0-9A-Fa-f]{6}", brand):
            raise ValueError(f"invalid source or colour: {provider_id}")
        original = assets_dir / entry["file"]
        raw = original.read_bytes()
        if not raw or len(raw) > 1024 * 1024:
            raise ValueError(f"empty or oversized asset: {provider_id}")
        digest = hashlib.sha256(raw).hexdigest()
        if digest != entry["sha256"]:
            raise ValueError(f"changed source asset: {provider_id}: {digest}")
        with tempfile.TemporaryDirectory(prefix="keykeeper-artwork-") as temp:
            png_file = Path(temp) / "logo.png"
            subprocess.run(
                ["sips", "-s", "format", "png", "-Z", "128", str(original), "--out", str(png_file)],
                check=True, capture_output=True, text=True,
            )
            png = png_file.read_bytes()
        if not png.startswith(b"\x89PNG\r\n\x1a\n"):
            raise ValueError(f"not a rendered PNG: {provider_id}")
        encoded = base64.b64encode(png).decode("ascii")
        template = ", isTemplate: true" if entry.get("template") else ""
        lines.append(
            f'        "{swift_string(provider_id)}": Mark(pngBase64: "{encoded}", '
            f'brandHex: "{brand}", source: "{swift_string(source)}"{template}),'
        )
        if wall_id not in by_id:
            raise ValueError(f"website brand missing: {wall_id}")
        mark = by_id[wall_id]
        mark.pop("letter", None)
        mark.pop("svg", None)
        mark.pop("viewBox", None)
        mark.pop("template", None)
        mark["brand"] = brand
        mark["png"] = encoded

    lines.extend(["    ]", "}", ""])
    swift = "\n".join(lines)
    website = json.dumps(wall, ensure_ascii=False, separators=(",", ":"), sort_keys=True) + "\n"
    return swift, website


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets-dir", required=True, type=Path)
    parser.add_argument("--website-wall", required=True, type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    swift, website = build(args.assets_dir, args.website_wall)
    if args.check:
        if SWIFT.read_text() != swift or args.website_wall.read_text() != website:
            raise SystemExit("provider artwork outputs are stale")
        print("provider artwork outputs match pinned sources")
        return
    SWIFT.write_text(swift)
    args.website_wall.write_text(website)
    print(f"synced {len(json.loads(MANIFEST.read_text()))} provider marks to App and website")


if __name__ == "__main__":
    main()
